sudo: false

language: python

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - make github

deploy:
  local-dir: output
  provider: pages
  skip-cleanup: true

  # Set in travis-ci.org dashboard, marked secure
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

